# Generated by Django 3.0.3 on 2020-03-12 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0002_entry'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topic',
            old_name='data_added',
            new_name='date_added',
        ),
        migrations.AlterField(
            model_name='topic',
            name='text',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
